version: '3'

services:
  api:
    image: ghcr.io/ta72-project/rust_actix_diesel
    ports:
      - "8000:8000"
    working_dir: "/app"
    volumes:
      - ".:/app"
    command: cargo watch --why -x run
    environment:
      DATABASE_URL: postgres://root:root@database/root
      CARGO_TARGET_DIR: /tmp/target

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
