version: '3'

services:
  api:
    image: ghcr.io/ta72-project/rust_actix_diesel
    ports:
      - "8000:8000"
    working_dir: "/app"
    volumes:
      - ".:/app"
    command: cargo watch --why -x run
    environment:
      DATABASE_URL: postgres://root:root@database/root
      CARGO_TARGET_DIR: /tmp/target

    healthcheck:
      test: curl localhost:8000/api
      start_period: 60s
    depends_on:
      - database

  database:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    healthcheck:
      test: pg_isready
      start_period: 1s
      start_interval: 1s
