// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `addresses` table.
    ///
    /// (Automatically generated by Diesel.)
    addresses (id) {
        /// The `id` column of the `addresses` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `number` column of the `addresses` table.
        ///
        /// Its SQL type is `Nullable<Int4>`.
        ///
        /// (Automatically generated by Diesel.)
        number -> Nullable<Int4>,
        /// The `street_name` column of the `addresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        street_name -> Text,
        /// The `postcode` column of the `addresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        postcode -> Text,
        /// The `city_name` column of the `addresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        city_name -> Text,
        /// The `complement` column of the `addresses` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        complement -> Nullable<Text>,
    }
}

diesel::table! {
    /// Representation of the `skills` table.
    ///
    /// (Automatically generated by Diesel.)
    skills (id) {
        /// The `id` column of the `skills` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `name` column of the `skills` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}

diesel::allow_tables_to_appear_in_same_query!(addresses, skills,);
