// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `skills` table.
    ///
    /// (Automatically generated by Diesel.)
    skills (id) {
        /// The `id` column of the `skills` table.
        ///
        /// Its SQL type is `Int8`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Int8,
        /// The `name` column of the `skills` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
    }
}
