name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose --locked

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --verbose --no-deps

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --verbose --locked

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --verbose --no-deps

  diesel:
    name: Diesel schema
    runs-on: ubuntu-latest
    container: rust_actix_diesel
    steps:
      - uses: actions/checkout@v3

      - name: Setup postgresql
        run: sudo systemctl start postgresql.service

      - name: Generate schema
        run: diesel setup --database-url postgres://postgres@127.0.0.1/diesel_schema

        # Checks for changed files
      - run: test ! "$(git status --porcelain)"
